In [15]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt

In [2]:
iris_dataset = datasets.load_iris()

for key, value in iris_dataset.items():
    print(key)

data
target
frame
target_names
DESCR
feature_names
filename
data_module


In [3]:
# Description of the data

print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [1]:
X = iris_dataset['data']
print(X.shape)
print(X)

NameError: name 'iris_dataset' is not defined

In [5]:
Y = iris_dataset['target']
print(Y.shape)
print(Y)

(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
X_max = X.max(axis=0)
X_min = X.min(axis=0)
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)

X_max, X_min, X_mean, X_std

(array([7.9, 4.4, 6.9, 2.5]),
 array([4.3, 2. , 1. , 0.1]),
 array([5.84333333, 3.05733333, 3.758     , 1.19933333]),
 array([0.82530129, 0.43441097, 1.75940407, 0.75969263]))

In [7]:
classes = dict()
for el in Y:
    if el not in classes:
        classes[el] = 1
    else:
        classes[el] += 1
    
classes

{0: 50, 1: 50, 2: 50}

In [8]:
class_1_indexes = np.argwhere(Y == 0)
print(class_1_indexes)
class_1_indexes = class_1_indexes.flatten()
print(class_1_indexes)

class_1 = X[class_1_indexes]

print(class_1.shape)
print(class_1)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
(50, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2

In [9]:
class_2 = X[np.argwhere(Y == 1).flatten()]
class_3 = X[np.argwhere(Y == 2).flatten()]

In [14]:
class_1_max = class_1.max(axis=0)
class_2_max = class_2.max(axis=0)
class_3_max = class_3.max(axis=0)

class_1_min = class_1.min(axis=0)
class_2_min = class_2.min(axis=0)
class_3_min = class_3.min(axis=0)

class_1_mean = class_1.mean(axis=0)
class_2_mean = class_2.mean(axis=0)
class_3_mean = class_3.mean(axis=0)

class_1_std = class_1.std(axis=0)
class_2_std = class_2.std(axis=0)
class_3_std = class_3.std(axis=0)


print('max class 1:', class_1_max)
print('max class 2:', class_2_max)
print('max class 3:', class_3_max)

print('min class 1:', class_1_min)
print('min class 2:', class_2_min)
print('min class 3:', class_3_min)

print('mean class 1:', class_1_mean)
print('mean class 2:', class_2_mean)
print('mean class 3:', class_3_mean)

print('std class 1:', class_1_std)
print('std class 2:', class_2_std)
print('std class 3:', class_3_std)

max class 1: [5.8 4.4 1.9 0.6]
max class 2: [7.  3.4 5.1 1.8]
max class 3: [7.9 3.8 6.9 2.5]
min class 1: [4.3 2.3 1.  0.1]
min class 2: [4.9 2.  3.  1. ]
min class 3: [4.9 2.2 4.5 1.4]
mean class 1: [5.006 3.428 1.462 0.246]
mean class 2: [5.936 2.77  4.26  1.326]
mean class 3: [6.588 2.974 5.552 2.026]
std class 1: [0.34894699 0.37525458 0.17191859 0.10432641]
std class 2: [0.51098337 0.31064449 0.46518813 0.19576517]
std class 3: [0.62948868 0.31925538 0.54634787 0.27188968]
